name: Test module installation
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: canary
      - run: |
          deno install --allow-all --force --name run ./run/bin/cmd.ts
          echo "$HOME/.deno/bin" >> $GITHUB_PATH
      - run: run

     
